#!/bin/sh

DIRECTORY="$HOME/.bgimgs/"

if [ ! -d "$DIRECTORY" ]; then
	echo "Error: directory does not exist"
	exit 1
	fi

FILES=$(ls "$DIRECTORY")

NUM_FILES=$(echo "$FILES" | wc -l)

RAND_NUM=$(( $(date +%s) % $NUM_FILES + 1))

FILE_NAME=$(echo "$FILES" | sed -n "${RAND_NUM}p")

xwallpaper --zoom $DIRECTORY/$FILE_NAME
